# Generated by Django 6.1.1 on 2026-09-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=100)),
                ('stu_email', models.EmailField(max_length=254, unique=True)),
                ('stu_city', models.CharField(max_length=100)),
                ('stu_add', models.TextField()),
            ],
        ),
    ]
