# Generated by Django 6.0.7 on 2026-07-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('city', models.CharField(choices=[('Bhopal', 'Bhopal'), ('Indore', 'Indore'), ('Delhi', 'Delhi'), ('Mumbai', 'Mumbai'), ('Pune', 'Pune')], max_length=20)),
                ('image', models.ImageField(upload_to='student_images/')),
                ('resume', models.FileField(upload_to='student_resume/')),
                ('password', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('qualification', models.CharField(choices=[('10th', '10th'), ('12th', '12th'), ('Diploma', 'Diploma'), ('BCA', 'BCA'), ('B.Tech', 'B.Tech'), ('MCA', 'MCA'), ('M.Tech', 'M.Tech'), ('Other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
