# Generated by Django 6.0.7 on 2026-07-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_examform'),
    ]

    operations = [
        migrations.AddField(
            model_name='examform',
            name='subject',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
