# Generated by Django 6.0.7 on 2026-07-23 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_examform_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examform',
            name='subject',
        ),
    ]
